version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  docker-setup:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker
 
  server-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          command: npm test
          working_directory: ./server

  client-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./client
      - run:
          command: npm test
          working_directory: ./client

  docker-publish:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            echo "$DOCKER_LOGIN" | docker login -u "wojow8" --password-stdin
            sudo docker build ./server -t wojow8/srv
            sudo docker push wojow8/srv
      - run:
          command: |
            echo "$DOCKER_LOGIN" | docker login -u "wojow8" --password-stdin
            sudo docker build ./client -t wojow8/cli
            sudo docker push wojow8/cli
   
workflows:
    build-and-test:
      jobs:
        - docker-setup
        - server-test:
          filters:
            branches:
             only:
               - master
        - client-test:
          filters:
            branches:
             only:
               - master
        - docker-publish:
            requires:
              - docker-setup
              - server-test
              - client-test       
