version: 2.1
orbs:
    node: circleci/node@2.1.0
jobs:
    build-and-test:
        executor: node/default
        working_directory: ~/repo
        steps:
        - checkout
        - node/install-packages
        - run: 
            command: npm install
            working_directory: ./server
            command: npm test
        run:
            command: npm install
            working_directory: ./client
            command: npm test
workflows:
    build-test-and-deploy:
        jobs:
        - build-and-test

