version: 2.1
orbs:
    node: circleci/node@2.1.0
jobs:
    build-and-test:
        executor: node/default
        steps:
        - checkout
        - run: npm install
        - run: npm test
workflows:
    build-test-and-deploy:
        jobs:
        - build-and-test
